import type { Metadata } from "next";
import { Geist, Geist_Mono, Imperial_Script } from "next/font/google";
import LocalFont from "next/font/local";
import "./globals.css";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const imperialScript = Imperial_Script({
  variable: "--font-imperial-script",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
}); 

export const aeonik = LocalFont({
  src: [
    { path: "./fonts/Aeonik-Regular.ttf", weight: "400", style: "normal" },
  ],
  variable: "--font-aeonik",
  display: "swap",
});

export const newsreader = LocalFont({
  src: [
    { path: "./fonts/Newsreader-italic.ttf", weight: "400", style: "italic" },
  ],
  variable: "--font-newsreader",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${aeonik.variable} ${imperialScript.variable} ${newsreader.variable} font-sansantialiased`}
      >
        <h2 className="text-2xl font-bold ">Resume<span className=" text-teal-700">AI</span></h2>
        {children}
      </body>
    </html>
  );
}
